# fly.toml file generated for themcunetwork on 2023-03-29T14:30:38+08:00

app = "themcunetwork"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sin"

[build]
  image = "nruizjr/themcunetwork:latest"

[env]
  ASPNETCORE_URLS = "http://+:8080"
  CloudinarySettings__ApiKey = "498714814261394"
  CloudinarySettings__CloudName = "ruiznj"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
